# Generated by Django 2.2.4 on 2020-05-08 04:29

import django.contrib.postgres.fields
from django.db import migrations, models
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_userproject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectboard',
            name='statuses',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), default=projects.models.get_default_statuses, size=None),
        ),
    ]
