# Generated by Django 2.2.4 on 2020-05-08 06:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0004_auto_20200508_1002'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userprojectrelation',
            unique_together={('pbid', 'user')},
        ),
    ]
